bazel_build:
  container:
    image: l.gcr.io/google/bazel:2.1.0
  task:
    bazel_repository_cache:
      folder: /.repo_cache
      fingerprint_script: cat WORKSPACE
      populate_script: mkdir -p /.repo_cache && bazel  --bazelrc=.cirrus.bazelrc fetch --repository_cache=/.repo_cache //...
    test_script:
    - bazel  --bazelrc=.cirrus.bazelrc test --jobs=2 --flaky_test_attempts=3 --repository_cache=/.repo_cache -k --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST //...
    always:
      junit_result_artifacts:
        path: "bazel-testlogs/**/test.xml"
        format: junit