docker_builder:
  name: test
  environment:
    V: 2.1.0
  bazel_installation_script:
      - |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mv bazelisk-linux-amd64 "/usr/bin/bazel"
          chmod +x /usr/bin/bazel
  bazel_repository_cache:
    folder: /.repo_cache
    fingerprint_script: cat WORKSPACE
    populate_script: mkdir -p /.repo_cache && bazel  --bazelrc=.cirrus.bazelrc fetch --repository_cache=/.repo_cache //...

  test_script:
  - bazel  --bazelrc=.cirrus.bazelrc test --repository_cache=/.repo_cache -k --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST //...
  always:
    junit_result_artifacts:
      path: "bazel-testlogs/**/test.xml"
      format: junit