bazel_build:
  name: test
  container:
    image: l.gcr.io/google/bazel:2.2.0
  
  environment:
    XDG_CACHE_HOME: /xdg_cache

  task:
    bazelisk_installation_script:
      - |
        rm /usr/local/bin/bazel
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
        mv bazelisk-linux-amd64 "/usr/bin/bazel"
        chmod +x /usr/bin/bazel
        which bazel
            
    bazelisk_cache:
      folder: $XDG_CACHE_HOME
      fingerprint_script: cat .bazelversion
      populate_script: mkdir -p $XDG_CACHE_HOME && bazel version

    bazel_repository_cache:
      folder: /.repo_cache
      fingerprint_script: cat WORKSPACE
      populate_script: mkdir -p /.repo_cache && bazel  --bazelrc=.cirrus.bazelrc fetch --repository_cache=/.repo_cache //...

    test_script:
    - bazel  --bazelrc=.cirrus.bazelrc test --config=ut-only --repository_cache=/.repo_cache -k --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST //...

    integration_test_script:
    - bazel  --bazelrc=.cirrus.bazelrc test --config=it --repository_cache=/.repo_cache -k --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST //...
    
    always:
      junit_result_artifacts:
        path: "bazel-testlogs/**/test.xml"
        format: junit
