
version: 2.1
jobs:
  build:
    docker:
      - image: l.gcr.io/google/bazel:3.4.1
    steps:
      - checkout
      - run:
          name: Execute bazel
          command: |-
              cd getting-started/greyhound-app
              sh gradlew bootBuildImage --imageName=wixpress/greyhound-app
              cd ../..
              
              # Set environment variables
              # Install Bazelisk
              rm /usr/local/bin/bazel
              curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-linux-amd64"
              mv bazelisk-linux-amd64 /usr/bin/bazel
              chmod +x /usr/bin/bazel
              which bazel

              # Execute bazel
              bazel --bazelrc=.cirrus.bazelrc test --test_verbose_timeout_warnings --flaky_test_attempts=3 -k //...
      - run:
          name: Prepare results
          when: always
          command: |-
              rm -rf /tmp/bazel-testlogs
              mkdir -p /tmp/bazel-testlogs
              cp -r /root/project/bazel-testlogs/ /tmp/bazel-testlogs/
      - store_test_results:
          path: /tmp/bazel-testlogs
      - store_artifacts:
          path: /tmp/bazel-testlogs

